{{- if not .Values.peertube.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: peertube-custom-secret  # <--- Renamed to avoid duplicate error
stringData:                     # <--- Changed to stringData
  secret: {{ .Values.peertube.secret | quote }}
{{- end }}