{{- if not .Values.peertube.smtp.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: peertube-smtp
stringData:                 # <--- MUST BE 'stringData', NOT 'data'
  host: {{ .Values.peertube.smtp.host | quote }}
  port: {{ .Values.peertube.smtp.port | quote }}
  username: {{ .Values.peertube.smtp.username | quote }}
  password: {{ .Values.peertube.smtp.password | quote }}
{{- end }}