{{- if not .Values.peertube.admin.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: peertube-admin-secret
stringData:                     # <--- Changed to stringData
  email: {{ .Values.peertube.admin.email | quote }}       # <--- Key is 'email' to match Deployment
  password: {{ .Values.peertube.admin.password | quote }} # <--- Unconditional (Removed 'if')
{{- end }}